# Comment that will be sent if an issue is judged to be closed
comment: "This issue was closed because it does not meet our issue template layout. Please read it, and follow the prompting questions."
issueConfigs:
# There can be several configs for different kind of issues.
# Bug report
- content:
  - "Describe the bug"
  - "To Reproduce"
  - "Expected behavior"
  - "Additional context"
# Feature requests
- content:
  - "Motivation / Use Case"
  - "Expected Behavior"
  - "Other Information"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
