(ns orcpub.dnd.e5.character.random
  (:require [clojure.string :as s]))

(def calishite-names
  {::male ["Aseir"
          "Bardeid"
          "Haseid"
          "Khemed"
          "Mehmen"
          "Sudeiman"
          "Zashier"
          "Pasha"
          "Faruk"
          "Kwala"
          "Abbas"
          "Ashkan"
          "Ahmad"
          "Ali"
          "Amin"
          "Amir"
          "Ardashir"
          "Afshin"
          "Arshad"
          "Arman"
          "Armin"
          "Amir"
          "Arash"
          "Ardeshir"
          "Arvin"
          "Arwin"
          "Ashem"
          "Astash"
          "Bijan"
          "Babak"
          "Bahrom"
          "Bardia"
          "Basir"
          "Behnam"
          "Dalir"
          "Dariush"
          "Davoud"
          "Darafsh"
          "Ervin"
          "Erwin"
          "Ehsan"
          "Eskandar"
          "Esmail"
          "Izad"
          "Farhad"
          "Farbod"
          "Farrokh"
          "Farhid"
          "Giv"
          "Goshtasp"
          "Hamid"
          "Hassan"
          "Hirbod"
          "Hashem"
          "Hormuzd"
          "Jamshid"
          "Javad"
          "Kamran"
          "Karim"
          "Kasra"
          "Kazem"
          "Khashayr"
          "Khosrow"
          "Kiarash"
          "Kourosh"
          "Mazdak"
          "Mazdan"
          "Maziar"
          "Mehran"
          "Manuchehr"
          "Marduk"
          "Mehrdad"
          "Marzban"
          "Medhi"
          "Meysam"
          "Milad"
          "Mir"
          "Mithradates"
          "Musa"
          "Omid"
          "Papak"
          "Parizad"
          "Parsa"
          "Parviz"
          "Payam"
          "Pedram"
          "Piruz"
          "Pouria"
          "Ramin"
          "Reza"
          "Rostam"
          "Sadegh"
          "Sajad"
          "Saman"
          "Samir"
          "Sassan"
          "Sepehr"
          "Shahin"
          "Shapour"
          "Shahryar"
          "Shervin"
          "Sohrab"
          "Souroush"
          "Tirdad"
          "Turan"
          "Vahid"
          "Vandad"
          "Varshasp"
          "Yaghoub"
          "Yahya"
          "Younes"
          "Yazdan"
          "Zand"
          "Zartosht"
          "Zurvan"]
   ::female ["Atala"
            "Ceidil"
            "Hama"
            "Jasmal"
            "Meilil"
            "Seipora"
            "Yasheira"
            "Zasheida"
            "Oma"
            "Anahita"
            "Anousheh"
            "Arezu"
            "Ashraf"
            "Astar"
            "Atoosa"
            "Azar"
            "Azadeh"
            "Banu"
            "Baharak"
            "Farnaz"
            "Farnzaneh"
            "Fatemeh"
            "Fereshteh"
            "Goli"
            "Jaleh"
            "Katayoun"
            "Kiana"
            "Khorshid"
            "Laleh"
            "Leila"
            "Mandana"
            "Mahshid"
            "Maryam"
            "Mehregan"
            "Mina"
            "Mithra"
            "Mojugan"
            "Nasrin"
            "Nazanin"
            "Niloufar"
            "Parastu"
            "Pardis"
            "Parisa"
            "Parvin"
            "Payvand"
            "Reyhan"
            "Roksaneh"
            "Roya"
            "Roxana"
            "Sepideh"
            "Shirin"
            "Simin"
            "Soraya"
            "Sheila"
            "Sahar"
            "Tahmineh"
            "Taraneh"
            "Tarsa"
            "Tannaz"
            "Yasmin"
            "Yasamin"
            "Zarine"
            "Zhila"
            "Zaynab"]
   ::surname ["Basha"
             "Dumein"
             "Jassan"
             "Khalid"
             "Mostana"
             "Pashar"
             "Rein"
             "Abbasi"
             "Abed"
             "Ahura"
             "Ardavan"
             "Aria"
             "Armand"
             "Avesta"
             "Esfahani"
             "Esfandiari"
             "Farrokhzad"
             "Farahmand"
             "Ghorbani"
             "Gul"
             "Hanifnejad"
             "Hashemi"
             "Homayoun"
             "Hooshang"
             "Jahandar"
             "Jahangir"
             "Jahanshah"
             "Jamshidi"
             "Jang-Ju"
             "Kavoosi"
             "Kazemi"
             "Khadem"
             "Khiabani"
             "Khorasani"
             "Khorram-Din"
             "Lajani"
             "Lahijani"
             "Madani"
             "Mazdaki"
             "Mazdani"
             "Mehregan"
             "Mazandarani"
             "Mokri"
             "Mohsen"
             "Pahlavi"
             "Paria"
             "Parsi"
             "Pouran"
             "Rahbar"
             "Rajavi"
             "Rezaei"
             "Rostamian"
             "Sassani"
             "Shamshiri"
             "Shir-Del"
             "Shirazi"
             "Teymouri"
             "Tir"
             "Turan"
             "Turani"]})

(def chondathan-names
  {::male ["Darvin"
          "Dorn"
          "Evendur"
          "Gorstag"
          "Grim"
          "Helm"
          "Malark"
          "Morn"
          "Mirt"
          "Morn"
          "Kirt"
          "Mort"
          "Randal"
          "Stedd"
           "Reed"
           "Elric"
           "Wilmot"
           "Larkin"
           "Jackin"
           "Elis"
           "Cenric"
           "Cerdic"
           "Dunstan"
           "Eadwig"
           "Hrodulf"
           "Leofric"
           "Osgar"
           "Osmund"
           "Oswald"
           "Wulfric"
           "Wulfstan"
           "Wynnstan"
           "Wulfnod"]
   ::female ["Arveene"
            "Esvele"
            "Jhessail"
            "Kerri"
            "Lureene"
            "Miri"
            "Niri"
            "Rowan"
            "Shandri"
            "Shandra"
             "Tessele"
             "Royce"
             "Hild"
             "Hilda"
             "Wassa"
             "Mildryd"
             "Mildgyd"]
   ::surname-pre ["Amble"
                 "Buck"
                 "Dun"
                 "Even"
                 "Grey"
                 "Tall"
                 "Red"
                 "Green"
                 "Gold"
                 "Silver"
                  "High"
                  "Black"]
   ::surname-post ["crown"
                   "man"
                   "dragon"
                   "wood"
                   "castle"
                   "stag"
                   "sail"
                   "hammer"
                   "mast"
                   "staff"]})

;; macedonian based
(def damaran-names
  {::male ["Bor"
          "Fodel"
          "Glar"
          "Grigor"
          "Igan"
          "Ivor"
          "Kosef"
          "Mival"
          "Orel"
          "Pavel"
          "Sergor"
          "Andon"
          "Bogdan"
          "Bogomil"
          "Bojan"
          "Darko"
          "Dragan"
          "Emil"
          "Kiril"
          "Kliment"
          "Vasko"
          "Dzvonko"
          "Dimitar"]
   ::male-pre ["To"
              "Ho"
              "Ris"
              "Mir"
              "Mar"
              "Jor"
              "Jo"
              "I"
              "Gli"
              "Gri"
              "E"
              "Dar"
              "Bor"]
   ::male-post ["do"
               "dor"
               "to"
               "ko"
               "tej"
               "dan"
               "sif"
               "vo"
               "sim"
               "gor"
               "mil"]
   ::female ["Alethra"
            "Kara"
            "Katernin"
            "Mara"
            "Natali"
            "Olma"
            "Tana"
            "Zora"
            "Bogdana"
            "Dafina"
            "Danica"
            "Dragana"
            "Elena"
            "Gordana"
            "Gorica"
            "Vaska"
            "Vera"
            "Vesna"]
   ::female-pre ["Dan"
                "Daf"
                "Gal"
                "Fros"
                "Filim"
                "Is"
                "Iv"
                "Jasm"
                "Jord"
                "Kal"
                "Kat"
                "Lilj"
                "Lid"
                "Mar"
                "Melan"
                "Mil"
                "Mir"
                "Rum"
                "Ram"
                "Sof"]
   ::female-post ["ica"
                 "ina"
                 "ana"
                 "ena"
                 "ona"
                 "ija"]
   ::surname ["Bersk"
             "Chernin"
             "Dotsk"
             "Kulenov"
             "Marsk"
             "Nemetsk"
             "Shemov"
             "Starag"]
   ::surname-pre ["Mark"
                 "Panch"
                 "Naum"
                 "Nikol"
                 "Lazar"
                 "Koch"
                 "Ilich"
                 "Jan"
                 "Jovan"
                 "Stojon"
                 "Rus"
                 "Rist"
                 "Ris"
                 "Pand"
                 "Petk"
                 "Mitr"]
   ::surname-post ["ev"
                   "ov"
                   "ovsk"
                   "ovski"
                   "evski"
                   "evsk"
                   "esk"
                   "eski"
                   "etsk"]})

(def turami-names
  {::male ["Anton"
          "Diero"
          "Marcon"
          "Pieron"
          "Rimardo"
          "Romero"
          "Salazar"
          "Umbero"]
   ::male-pre ["An"
              "Pie"
              "Ri"
              "Sala"
              "Mar"
              "Die"
              "Ba"
              "Ab"
              "Bar"]
   ::male-post ["ro"
               "dol"
               "tol"
               "ron"
               "con"
               "bero"
               "zar"
               "mardo"
               "kar"]
   ::female ["Balama"
            "Dona"
            "Faila"
            "Jalana"
            "Luisa"
            "Marta"
            "Quara"
            "Selise"
            "Vonda"]
   ::female-pre ["Do"
                "Bala"
                "Aba"
                "Qua"
                "Seli"
                "Von"
                "Lui"
                "Ara"
                "Bibi"]
   ::female-post ["da"
                 "na"
                 "sa"
                 "ma"
                 "se"
                 "rne"
                 "ne"]
   ::surname ["Agosto"
             "Astorio"
             "Calabra"
             "Domine"
             "Falone"
             "Marivaldi"
             "Pisacar"
             "Ramondo"
             "Aroztegi"
             "Bidarte"
             "Bolibar"
             "Elkano"
             "Elizondo"
             "Etxandi"
             "Etxarte"
             "Etxeberri"
             "Ibarra"
             "Lekubarri"
             "Loiola"
             "Mendiluze"
             "Urberoaga"
             "Zabala"
             "Zubiondo"
             "Eneko"]
   ::surname-pre ["Mari"
                 "Asta"
                 "Asto"
                 "Do"
                 "Cala"
                 "Pisa"
                 "I"
                 "Za"]
   ::surname-post ["buri"
                  "buru"
                  "lando"
                  "mondo"
                  "car"
                  "rte"
                  "neko"
                  "gorri"
                  "turri"
                  "luze"
                  "bala"
                  "kano"
                  "xarte"
                  "zondo"
                  "barri"]})

(def shou-names
  {::male ["An"
          "Chen"
          "Chi"
          "Fai"
          "Jiang"
          "Jun"
          "Lian"
          "Long"
          "Meng"
          "On"
          "Shan"
          "Shui"
          "Wen"
          "Li"
          "Ling"
          "Sheng"
          "Si"
          "Song"
          "Zhao"]
   :pre ["Ji"
         "Xi"
         "J"
         "M"
         "Ch"
         "Chi"
         "Sh"
         "Shi"
         "L"
         "Li"
         "F"
         "Fi"]
   :post ["ang"
          "an"
          "eng"
          "ong"
          "en"
          "on"]
   ::surname ["Chien"
             "Huang"
             "Kao"
             "Kung"
             "Lao"
             "Ling"
             "Mei"
             "Pin"
             "Shin"
             "Sum"
             "Tan"
             "Wan"
             "Wu"
             "Kong"
             "Ma"
             "Cheng"
             "Tan"
             "He"
             "Hu"
             "Mao"]
   ::female ["Bai"
            "Chao"
            "Jia"
            "Lie"
            "Mei"
            "Qiao"
            "Shui"
            "Tai"
            "Fen"
            "Fan"
            "Hui"
            "Ju"
            "Jun"
            "Lan"
            "Lei"
            "Liling"
            "Min"
            "Liu"
            "Nuo"
            "Shu"
            "Qiu"
            "Ting"
            "Wei"
             "Wen"]})

(def illuskan-names
  {::male ["Ander"
          "Blath"
          "Bran"
          "Frath"
          "Geth"
          "Lander"
          "Luth"
          "Malcer"
          "Stor"
          "Taman"
           "Urth"
           "Alwyn"
           "Andras"
           "Anwen"
           "Arwyn"
           "Bron"
           "Brin"
           "Delwyn"
           "Drystan"
           "Emlyn"
           "Gareth"
           "Glendower"
           "Gwil"
           "Gwilym"
           "Gwyn"
           "Ilar"
           "Ivor"
           "Madoc"
           "Maldwyn"
           "Meuric"
           "Morgan"
           "Owena"
           "Pryce"
           "Rhodri"
           "Rhydderch"
           "Roderick"
           "Sawyl"
           "Sieffre"
           "Siorus"
           "Talfryn"
           "Taliesin"
           "Trystan"
           "Tudor"
           "Urien"
           "Wynfor"
           "Tomi"]
   ::female ["Amafrey"
             "Betha"
             "Cefrey"
             "Kethra"
             "Mara"
             "Olga"
             "Silifrey"
             "Westra"
             "Carys"
             "Ceri"
             "Delwyn"
             "Delyth"
             "Deryn"
             "Elain"
             "Eurwen"
             "Gaenor"
             "Glenda"
             "Glenys"
             "Glynn"
             "Gwen"
             "Gwenda"
             "Olwyn"
             "Owena"
             "Rhian"
             "Rhiannon"
             "Rhonwen"
             "Rhosyn"
             "Siana"
             "Sian"
             "Siwan"
             "Tegan"
             "Winifrey"
             "Willafrey"]
   ::surname-pre ["Wind"
                  "Storm"
                  "Bright"
                  "Horn"
                  "Lack"
                  "Stead"
                  "Sky"
                  "Green"
                  "Gray"
                  "Black"
                  "Fall"
                  "Summer"
                  "Spring"
                  "Winter"
                  "Ice"]
   ::surname-post ["rivver"
                   "wood"
                   "man"
                   "hallow"
                   "harrow"
                   "fforest"
                   "llost"
                   "water"
                   "mor"
                   "mount"
                   "grass"
                   "raven"
                   "hawk"
                   "wave"
                   "crow"
                   "shear"
                   "sea"
                   "lake"
                   "wolf"]})

(def rashemi-names
  {::male ["Borivik"
           "Faurgar"
           "Jandar"
           "Kanithar"
           "Madislak"
           "Ralmevik"
           "Shaumar"
           "Vladislak"
           "Bogdan"
           "Bogumir"
           "Milodrag"]
   ::pre ["Madi"
          "Vladi"
          "Ludi"
          "Kani"
          "Brato"
          "Desi"
          "Drago"
          "Kazi"
          "Lyud"
          "Radomir"
          "Rosti"
          "Stanis"
          "Sobe"
          "Tomi"
          "Veli"
          "Vito"
          "Valsti"
          "Vsevo"
          "Yaro"
          "Zvoni"]
   ::male-post ["slak"
                "vik"
                "mar"
                "thar"
                "mir"
                "mil"]
   ::female ["Fyevarra"
             "Hulmarra"
             "Immith"
             "Imzel"
             "Navarra"
             "Shevarra"
             "Tammith"
             "Yuldra"
             "Bogdana"
             "Bozhena"
             "Elena"]
   ::female-post ["slaka"
                  "vika"
                  "mara"
                  "thara"]
   ::surname-pre ["Char"
                  "Iltazy"
                  "Murnye"
                  "Staya"
                  "Ulmo"
                  "Nau"
                  "Ned"
                  "Novo"
                  "Ognya"
                  "Pakul"
                  "Pade"
                  "Pav"
                  "Pavi"
                  "Pavlo"
                  "Pecha"
                  "Pia"
                  "Pulkra"
                  "Rezni"
                  "Rudaw"
                  "Sla"
                  "Soko"
                  "Stol"
                  "Svoba"
                  "Trifo"
                  "Vanche"
                  "Velich"
                  "Wola"
                  "Zabe"
                  "Zori"]
   ::surname-post ["yov"
                   "kov"
                   "mov"
                   "vic"
                   "til"
                   "lek"
                   "goba"
                   "yara"
                   "thara"
                   "noga"
                   "kina"
                   "balek"
                   "vak"
                   "sad"
                   "nov"
                   "lov"
                   "tek"
                   "bek"
                   "zak"
                   "zyk"]})

(def mulan-names
  {::male ["Aos"
           "Adiur"
           "Abil-Ili"
           "Ahimelek"
           "Alaparos"
           "Alorus"
           "Amatnim"
           "Amelagar"
           "Amempsin"
           "Anshar"
           "Ardates"
           "Belibni"
           "Bel-Samu"
           "Dagan"
           "Dapinu"
           "Boktnassar"
           "Duzi"
           "Gamil"
           "Gahal"
           "Gadatas"
           "Gobryas"
           "Haban"
           "Hassimir"
           "Igigi"
           "Immertum"
           "Irshusin"
           "Itti-Bel"
           "Iva"
           "Kara-Bel"
           "Kha-Hea"
           "Lakhmu"
           "Lidan-Gula"
           "Maruduk"
           "Moumis"
           "Murdus"
           "Nabu"
           "Nabua"
           "Nabu-Ikbi"
           "Namtar"
           "Naramsin"
           "Nazaratus"
           "Nebo"
           "Ninib"
           "Ninip"
           "Ramman"
           "Samas"
           "Sar"
           "Sar-Ili"
           "Sharyukin"
           "Silani"
           "Suzub"
           "Tammuz"
           "Tamzi"
           "Uras"
           "Zur"]
   ::female ["Arizima"
             "Chathi"
             "Nephis"
             "Nulara"
             "Murithi"
             "Sefris"
             "Thola"
             "Umara"
             "Zolis"
             "Allatu"
             "Anatu"
             "Anunit"
             "Aralu"
             "Aruru"
             "Atanah-Ili"
             "Belatsunat"
             "Belili"
             "Belit"
             "Damkina"
             "Davcina"
             "Davke"
             "Ellat-Gula"
             "Gula"
             "Ishtar"
             "Istar"
             "Kishar"
             "Kissare"
             "Mot"
             "Mummu"
             "Mylitta"
             "Nana"
             "Ni"
             "Nin-Marki"
             "Omarosa"
             "Ri"
             "Rubati"
             "Sabitum"
             "Shala"
             "Tauthe"
             "Zirat-Banit"]
   ::surname ["Adrahasis"
              "Adapa"
              "Ahiyababa"
              "Akki"
              "Almelon"
              "Ammenon"
              "Ammidikaga"
              "Amurkkan"
              "Anunnaki"
              "Arakhu"
              "Ardusin"
              "Arua"
              "Asardin"
              "Awil"
              "Balasu"
              "Belteshazzar"
              "Berosus"
              "Baktnassar"
              "Chinzirus"
              "Gadatas"
              "Gahal"
              "Gamil"
              "Gandu"
              "Gobryas"
              "Gudea"
              "Harbshihu"
              "Ibilsin"
              "Immertum"
              "Irigbel"
              "Ishum"
              "Kandalanu"
              "Labynetus"
              "Kurigalzu"
              "Nabonidus"
              "Naditabirus"
              "Orchamus"
              "Otiartes"
              "Putur"
              "Sadudu"
              "Sargina"
              "Sardanapalus"
              "Shukura"
              "Sin"
              "Sisit"
              "Sumai"
              "Tu"
              "Urhammu"
              "Zabu"]})

(def elf-names
  {::male ["Adran"
           "Aelar"
           "Aramil"
           "Arrannis"
           "Aust"
           "Beiro"
           "Berrian"
           "Carric"
           "Enialis"
           "Erdan"
           "Erevan"
           "Galinndan"
           "Hadarai"
           "Heian"
           "Himo"
           "Immeral"
           "Ivellios"
           "Laucian"
           "Mindartis"
           "Paelias"
           "Peren"
           "Quarion"
           "Riardon"
           "Rolen"
           "Soveliss"
           "Thamior"
           "Theren"
           "Varis"]
   ::male-pre ["Ad"
               "Ae"
               "Pae"
               "Pe"
               "Tha"
               "The"
               "Sove"
               "Qua"
               "Mina"
               "Hadda"
               "Lau"
               "Ive"
               "Enia"
               "Car"
               "Be"
               "Arra"]
   ::male-post ["rris"
                "ris"
                "rai"
                "rrai"
                "tis"
                "ran"
                "rran"
                "rian"
                "rrian"
                "ren"
                "rren"
                "liss"
                "lis"
                "llis"
                "lar"
                "llar"
                "lias"
                "llias"
                "liar"
                "lliar"
                "lior"
                "llior"
                "mior"
                "rion"
                "rtis"
                "cian"
                "llios"
                "lios"
                "ric"
                "nis"
                "nnis"]
   ::female ["Adrie"
             "Althaea"
             "Anastrianna"
             "Andraste"
             "Antinua"
             "Bethrynna"
             "Birel"
             "Caelynn"
             "Drusilia"
             "Enna"
             "Felosial"
             "Ielenia"
             "Jelenneth"
             "Keyleth"
             "Leshanna"
             "Lia"
             "Meriele"
             "Mialee"
             "Naivara"
             "Quelanna"
             "Quillathe"
             "Sariel"
             "Shanairra"
             "Shava"
             "Silaqui"
             "Theirsatra"
             "Thia"
             "Vadania"
             "Valanthe"
             "Xanaphia"]
   ::female-pre ["A"
                 "Ana"
                 "Dru"
                 "Cae"
                 "Felo"
                 "Ie"
                 "Le"
                 "Key"
                 "Me"
                 "Mia"
                 "Nai"
                 "Sil"
                 "Xana"
                 "Thie"
                 "Va"
                 "Qui"
                 "Sa"
                 "Thia"]
   ::female-post ["thaea"
                  "strianna"
                  "lenneth"
                  "rianna"
                  "raste"
                  "draste"
                  "rynna"
                  "lynn"
                  "silia"
                  "sial"
                  "lenia"
                  "leth"
                  "shanna"
                  "riele"
                  "vara"
                  "riel"
                  "nairra"
                  "va"
                  "rsatra"
                  "phia"
                  "laqui"
                  "dania"
                  "lanthe"
                  "llath"
                  "lee"]
   ::surname ["Amakiir"
              "Amastacia"
              "Galanodel"
              "Holimion"
              "Ilphelkiir"
              "Liadon"
              "Meliamne"
              "Nailo"
              "Siannodel"
              "Xiloscient"]
   ::surname-pre ["Mith"
                  "Ald"
                  "Tor"
                  "Eal"
                  "Kev"
                  "Lan"
                  "Nor"
                  "Mithr"
                  "Mithd"
                  "Mithy"
                  "Cel"
                  "Amast"
                  "Am"
                  "Ilph"
                  "Xil"
                  "Tal"
                  "Und"
                  "Tath"
                  "El"
                  "Ond"]
   ::surname-post ["aviel"
                   "amirta"
                   "osum"
                   "adhrinian"
                   "ethryl"
                   "oval"
                   "aiseer"
                   "etaryl"
                   "acia"
                   "elkiir"
                   "akiir"
                   "oscient"
                   "aiil"
                   "oeme"
                   "elon"
                   "enval"
                   "irmae"
                   "athir"
                   "olithe"]})

(def dwarf-names
  {::male ["Adrik"
           "Alberich"
           "Baern"
           "Barenedd"
           "Brottor"
           "Bruenor"
           "Dain"
           "Darrak"
           "Delg"
           "Eberk"
           "Einkil"
           "Fargrim"
           "Flint"
           "Gardain"
           "Harbek"
           "Kildrak"
           "Morgran"
           "Orsik"
           "Oskar"
           "Rangrim"
           "Rurik"
           "Taklinn"
           "Thoradin"
           "Thorin"
           "Tordek"
           "Traubon"
           "Travok"
           "Ulfgar"
           "Veit"
           "Vondal"]
   ::male-pre ["Tra"
               "Trau"
               "Tor"
               "Tak"
               "Ru"
               "Ran"
               "Os"
               "Or"
               "Mor"
               "Thor"
               "Kil"
               "Har"
               "Gar"
               "Far"
               "Ein"
               "E"
               "Brue"
               "Dar"
               "Bro"
               "Brog"
               "Delg"
               "Dalg"
               "Drag"]
   ::male-post ["dan"
                "den"
                "din"
                "nor"
                "ner"
                "nir"
                "dal"
                "del"
                "bon"
                "ben"
                "rak"
                "rek"
                "rik"
                "grim"
                "gram"
                "kil"
                "kel"
                "kal"
                "dain"
                "drak"
                "drek"
                "drik"
                "bek"
                "bik"
                "sik"
                "sek"
                "sok"
                "dek"
                "dik"
                "vok"
                "vik"
                "vek"
                "vak"
                "kar"
                "ker"
                "kir"
                "berk"
                "birk"
                "ttor"]
   ::female ["Amber"
             "Artin"
             "Audhild"
             "Bardryn"
             "Dagnal"
             "Diesa"
             "Eldeth"
             "Falkrunn"
             "Finellen"
             "Gunnloda"
             "Gurdis"
             "Helja"
             "Hlin"
             "Kathra"
             "Kristryd"
             "Ilde"
             "Liftrasa"
             "Mardred"
             "Riswynn"
             "Sannl"
             "Torbera"
             "Torgga"
             "Vistra"]
   ::female-pre ["Fine"
                 "Aud"
                 "Bar"
                 "Gunn"
                 "Gur"
                 "Hel"
                 "Ka"
                 "Kri"
                 "Lift"
                 "Mar"
                 "Ris"
                 "Tor"
                 "Vis"]
   ::female-post ["stryd"
                  "dred"
                  "wynn"
                  "rgga"
                  "ja"
                  "ga"
                  "hild"
                  "dryn"
                  "tin"
                  "llen"
                  "deth"
                  "loda"
                  "lis"
                  "dis"
                  "thra"
                  "rasa"
                  "berra"]
   ::surname ["Balderk"
              "Battlehammer"
              "Brawnanvil"
              "Dankil"
              "Fireforge"
              "Frostbeard"
              "Gorunn"
              "Holderhek"
              "Ironfist"
              "Loderr"
              "Lutgehr"
              "Rumnaheim"
              "Strakeln"
              "Torunn"
              "Ungart"]
   ::surname-pre-1 ["Battle"
                    "Iron"
                    "Fire"
                    "Brawn"
                    "Oaken"
                    "Stout"
                    "Fast"
                    "Swift"
                    "Hard"
                    "War"
                    "Broad"]
   ::surname-post-1 ["axe"
                     "hammer"
                     "fist"
                     "beard"
                     "forge"
                     "anvil"
                     "shield"
                     "helm"]
   ::surname-pre-2 ["Bal"
                    "Bel"
                    "Rumna"
                    "Stra"
                    "Un"
                    "On"
                    "An"
                    "Ald"
                    "Eld"
                    "Aud"
                    "Lut"
                    "Lat"
                    "Go"
                    "God"
                    "To"
                    "Tod"]
   ::surname-post-2 ["derk"
                     "berk"
                     "heim"
                     "keln"
                     "gart"
                     "gert"
                     "gehr"
                     "gahr"
                     "gar"
                     "gorr"
                     "runn"]})

(def halfling-names
  {::male ["Alton"
           "Ander"
           "Cade"
           "Corrin"
           "Eldon"
           "Errich"
           "Finnan"
           "Garret"
           "Lindal"
           "Lyre"
           "Merric"
           "Milo"
           "Osborn"
           "Perrin"
           "Reed"
           "Roscoe"
           "Wellby"
           "Aidan"
           "Andreas"
           "Angus"
           "Ardal"
           "Bevin"
           "Clancy"
           "Colin"
           "Conley"
           "Connor"
           "Cowal"
           "Daley"
           "Declan"
           "Domnall"
           "Fergus"
           "Fillin"
           "Finbar"
           "Finnegan"
           "Finnen"
           "Flann"
           "Garvin"
           "Gilroy"
           "Keegan"
           "Keelan"
           "Killian"
           "Leary"
           "Lorcan"
           "Mahon"
           "Murrow"
           "Nevan"
           "Odran"
           "Osheen"
           "Paddy"
           "Quinn"
           "Redmund"
           "Rowan"
           "Seanan"
           "Sweeney"
           "Tierney"
           "Roderic"
           "Beren"
           "Ladderic"
           "Garreth"
           "Finnegan"
           "Gage"
           "Carrow"
           "Alderic"
           "Darrow"
           "Onderic"
           "Wilrich"
           "Wenton"
           "Pimsire"
           "Flyngin"
           "Errin"
           "Olo"
           "Fosco"
           "Hob"
           "Osborn"
           "Theadric"
           "Sam"
           "Willaby"]
   ::female ["Andry"
             "Bree"
             "Callie"
             "Cora"
             "Euphemia"
             "Jillian"
             "Kithri"
             "Lavinia"
             "Lidda"
             "Merla"
             "Nedda"
             "Paela"
             "Portia"
             "Seraphina"
             "Shaena"
             "Trym"
             "Vani"
             "Verna"
             "Brianne"
             "Dora"
             "Jilly"
             "Marla"
             "Shanna"
             "Shauna"
             "Marta"
             "Dina"
             "Dana"
             "Lidia"
             "Cilia"
             "Biddy"
             "Bridget"
             "Bridie"
             "Caitlin"
             "Darina"
             "Delma"
             "Devnet"
             "Eadan"
             "Edna"
             "Eilis"
             "Emer"
             "Fidelma"
             "Fiona"
             "Flann"
             "Gobnet"
             "Keeva"
             "Kiera"
             "Maura"
             "Mave"
             "Meave"
             "Mona"
             "Moyna"
             "Moyra"
             "Nola"
             "Nora"
             "Orla"
             "Patsy"
             "Quinn"
             "Roisin"
             "Rowan"
             "Shavonne"
             "Sheila"
             "Sile"
             "Sinead"
             "Tierney"
             "Treasa"
             "Una"
             "Poppy"
             "Polly"
             "Ruby"
             "Rose"
             "Peony"
             "Amaryllis"
             "Crystal"
             "Cora"
             "Gilly"
             "Lily"
             "Iris"]
   ::surname ["Hilltopple"
              "Dudley"
              "Dale"
              "Hamson"
              "Gardner"
              "Gamwich"
              "Burrows"
              "Talbot"]
   ::surname-pre ["Brush"
                  "Bush"
                  "Good"
                  "Green"
                  "High"
                  "Ivy"
                  "Sunny"
                  "Tea"
                  "Toss"
                  "Over"
                  "Under"
                  "Thorn"
                  "Tigh"
                  "Heather"
                  "Old"
                  "Linden"
                  "Mill"
                  "Proud"
                  "Stout"
                  "Swift"
                  "Teal"
                  "Tressle"
                  "Long"]
   ::surname-post ["gather"
                   "hill"
                   "barrel"
                   "bottle"
                   "breeze"
                   "topple"
                   "leaf"
                   "grass"
                   "bough"
                   "cobble"
                   "darrow"
                   "gallow"
                   "dimple"
                   "grove"
                   "pot"
                   "fern"
                   "spoon"
                   "gage"
                   "field"
                   "toe"
                   "jay"
                   "fur"
                   "brook"
                   "span"
                   "bridge"
                   "lark"
                   "meadow"
                   "wheel"
                   "haven"
                   "garden"
                   "stream"
                   "wood"
                   "apple"
                   "foot"
                   "body"
                   "finch"
                   "swallow"
                   "moss"
                   "bell"
                   "path"
                   "seed"
                   "heron"
                   "morn"]})

(defn name-search-match [text]
  (re-matches #".*\bname\b.*" text))

(defn first-last [list sex]
  (str (-> list sex rand-nth)
       " "
       (-> list ::surname rand-nth)))

(defn join-names [first last]
  (str first " " last))

(defn random-item [list key]
  (-> list key rand-nth))

(defn random-sex []
  (rand-nth [::male ::female]))

(derive ::tethyrian ::chondathan)

(defmulti random-name (fn [{:keys [race subrace sex]}]
                        (prn "RANDOM NAME" race subrace sex)
                        [race subrace sex]))

(defmethod random-name [::human ::calishite ::male] [_]
  (first-last calishite-names ::male))

(defmethod random-name [::human ::calishite ::female] [_]
  (first-last calishite-names ::female))

(defn chondathan-surname []
  (str (random-item chondathan-names ::surname-pre)
       (random-item chondathan-names ::surname-post)))

(defn chondathan-male-name []
  (str (random-item chondathan-names ::male-pre)
       (random-item chondathan-names ::male-post)))

(defmethod random-name [::human ::chondathan ::male] [_]
  (join-names
   (random-item chondathan-names ::male)
   (chondathan-surname)))

(defmethod random-name [::human ::chondathan ::female] [_]
  (join-names
   (random-item chondathan-names ::female)
   (chondathan-surname)))

(defn set-name [list type]
  (random-item list type))

(defn combined-name [list pre-type post-type]
  (str (random-item list pre-type)
       (random-item list post-type)))

(defn random-set-or-combined [list type pre-type post-type & [fraction-set]]
  (let [r (rand)]
    (if (< r (or fraction-set 0.2))
      (set-name list type)
      (combined-name list pre-type post-type))))

(defmethod random-name [::human ::turami ::male] [_]
  (join-names
   (random-set-or-combined turami-names ::male ::male-pre ::male-post)
   (random-set-or-combined turami-names ::surname ::surname-pre ::surname-post)))

(defmethod random-name [::human ::turami ::female] [_]
  (join-names
   (random-set-or-combined turami-names ::female ::female-pre ::female-post)
   (random-set-or-combined turami-names ::surname ::surname-pre ::surname-post)))

(defn shou-name [first]
  (join-names
   first
   (random-set-or-combined shou-names ::surname :pre :post)))

(defmethod random-name [::human ::shou ::male] [_]
  (shou-name
   (random-set-or-combined shou-names ::male :pre :post)))

(defmethod random-name [::human ::shou ::female] [_]
  (shou-name
   (random-set-or-combined shou-names ::female :pre :post)))

(defn damaran-name [first]
  (join-names
   first
   (random-set-or-combined damaran-names ::surname ::surname-pre ::surname-post)))

(defmethod random-name [::human ::damaran ::male] [_]
  (damaran-name
   (random-set-or-combined damaran-names ::male ::male-pre ::male-post)))

(defmethod random-name [::human ::damaran ::female] [_]
  (damaran-name
   (random-set-or-combined damaran-names ::female ::female-pre ::female-post)))

(defn illuskan-name [first]
  (join-names
   first
   (combined-name illuskan-names ::surname-pre ::surname-post)))

(defmethod random-name [::human ::illuskan ::male] [_]
  (illuskan-name
   (set-name illuskan-names ::male)))

(defmethod random-name [::human ::illuskan ::female] [_]
  (illuskan-name
   (set-name illuskan-names ::female)))

(defn rashemi-name [first]
  (join-names
   first
   (combined-name rashemi-names ::surname-pre ::surname-post)))

(defmethod random-name [::human ::rashemi ::male] [_]
  (rashemi-name
   (random-set-or-combined rashemi-names ::male ::pre ::male-post)))

(defmethod random-name [::human ::rashemi ::female] [_]
  (rashemi-name
   (random-set-or-combined rashemi-names ::female ::pre ::female-post)))

(defn mulan-name [first]
  (join-names
   first
   (set-name mulan-names ::surname)))

(defmethod random-name [::human ::mulan ::male] [_]
  (mulan-name
   (set-name mulan-names ::male)))

(defmethod random-name [::human ::mulan ::female] [_]
  (mulan-name
   (set-name mulan-names ::female)))

(def human-subraces
  [::calishite
   ::chondathan
   ::shou
   ::turami
   ::illuskan
   ::damaran
   ::rashemi
   ::mulan])

(def human-subraces-set
  (into #{} human-subraces))

(def races-and-subraces
  (concat (vec human-subraces)
          [::elf
           ::dwarf
           ::halfling]))

(defn random-race []
  (rand-nth
   [::elf
    ::dwarf
    ::halfling
    ::human
    ::human
    ::human]))

(defn random-human-subrace []
  (rand-nth human-subraces))

(defn random-subrace [race]
  (prn "RANDOM SUBRACE" race)
  (case race
    ::human (random-human-subrace)
    nil))

(defn random-race-or-subrace []
  (rand-nth races-and-subraces))

(defn elf-name [first]
  (join-names
   first
   (random-set-or-combined elf-names ::surname ::surname-pre ::surname-post)))

(defmethod random-name [::elf nil ::male] [_]
  (elf-name
   (random-set-or-combined elf-names ::male ::male-pre ::male-post)))

(defmethod random-name [::elf nil ::female] [_]
  (elf-name
   (random-set-or-combined elf-names ::female ::female-pre ::female-post)))

(defn dwarf-name [first]
  (join-names
   first
   (apply random-set-or-combined dwarf-names (rand-nth [[::surname ::surname-pre-1 ::surname-post-1]
                                                         [::surname ::surname-pre-2 ::surname-post-2]]))))

(defmethod random-name [::dwarf nil ::male] [_]
  (dwarf-name
   (random-set-or-combined dwarf-names ::male ::male-pre ::male-post)))

(defmethod random-name [::dwarf nil ::female] [_]
  (dwarf-name
   (random-set-or-combined dwarf-names ::female ::female-pre ::female-post)))

(defn halfling-name [first]
  (join-names
   first
   (random-set-or-combined halfling-names ::surname ::surname-pre ::surname-post)))

(defmethod random-name [::halfling nil ::male] [_]
  (halfling-name
   (set-name halfling-names ::male)))

(defmethod random-name [::halfling nil ::female] [_]
  (halfling-name
   (set-name halfling-names ::female)))

(defn random-name-result [{:keys [sex race subrace]}]
  (prn "RANDOM NAME_RESULT" sex race subrace)
  (let [final-race (if (human-subraces-set subrace) ::human
                       (or race (random-race)))
        final-subrace (or subrace (random-subrace final-race))
        final-sex (or sex (random-sex))
        cfg {:race final-race
             :subrace final-subrace
             :sex final-sex}]
    (prn "AFERT" final-race final-subrace final-sex)
    (assoc cfg :name (random-name cfg))))

(def tavern-names
  {::pre ["Red"
          "Green"
          "Blue"
          "Purple"
          "Yellow"
          "Gray"
          "Black"
          "White"
          "Rusty"
          "Rusted"
          "Iron"
          "Copper"
          "Bronze"
          "Gold"
          "Golden"
          "Silver"
          "Platinum"
          "Fat"
          "Prancing"
          "Dancing"
          "Salty"
          "Giant"
          "Faithful"
          "Bearded"
          "Surly"
          "Brawling"
          "Fighting"
          "Horned"
          "Sunken"
          "Shaven"
          "Limping"
          "Lisping"
          "Smiling"
          "Laughing"
          "Smirking"
          "Quivering"
          "Silent"
          "Frosty"
          "Scorched"
          "Scorned"
          "Lucky"
          "Limber"
          "Mustachioed"
          "Tattooed"
          "Gelded"
          "Gilded"
          "Fierce"
          "Naked"
          "Leaping"
          "Gallivanting"
          "Gregarious"
          "Great"
          "Preening"
          "Pretentious"
          "Noble"
          "Wooden"
          "Woolen"
          "Forged"
          "Warty"
          "Flamboyant"
          "Swashbuckling"
          "Glamourous"
          "Resplendent"
          "Flaming"
          "Bombastic"
          "Dazzling"
          "Flatulent"
          "Bulging"
          "Barking"
          "Bursting"
          "Flirting"
          "Bawdy"
          "Flirtatious"
          "Flippant"
          "Ancient"
          "Olde"
          "Cheeky"
          "Waggish"
          "Fearless"
          "Bloated"
          "Starving"]
   ::post ["Goblin"
           "Dragon"
           "Manticore"
           "Griffin"
           "Orc"
           "Hobgoblin"
           "Stallion"
           "Mule"
           "Dog"
           "Monkey"
           "Clam"
           "Stag"
           "Goat"
           "Bear"
           "Bat"
           "Owlbear"
           "Dogfish"
           "Lobster"
           "Flumph"
           "Crab"
           "Wench"
           "Barmaid"
           "Mug"
           "Banshee"
           "Hag"
           "Harpy"
           "Mermaid"
           "Medusa"
           "Minotaur"
           "Bugbear"
           "Golem"
           "Troll"
           "Sprite"
           "Pixie"
           "Ogre"
           "Pegasus"
           "Kobold"
           "Half-Dragon"
           "Gnome"
           "Dryad"
           "Centaur"
           "Rust Monster"
           "Sword"
           "Shield"
           "Spear"
           "Dagger"
           "Halberd"
           "Quarterstaff"
           "Helm"
           "Mace"
           "Ship"
           "Sail"
           "Goblet"
           "Crown"
           "Mug"
           "Bow"
           "Quiver"
           "Gauntlet"
           "Fiend"
           "Hole"
           "Harp"
           "Flute"
           "Gem"
           "Diamond"
           "Emerald"
           "Ruby"
           "Tome"
           "Tomb"
           "Table"
           "Chair"
           "Throne"
           "Imp"
           "Blackfish"
           "Swordfish"
           "Satyr"]
   ::pre-2 ["The Manticore"
            "The Captain"
            "The Dragon"
            "The Red Dragon"
            "The Green Dragon"
            "The White Dragon"
            "The Gold Dragon"
            "The Dragon Turtle"
            "The Kraken"
            "The Aboleth"
            "The Bard"
            "The Warrior"
            "The Barbarian"
            "The Priest"
            "The Maiden"
            "The King"
            "The Queen"
            "The Duke"
            "The Griffon"
            "The Harpy"
            "The Medusa"
            "The Goblin"
            "The Hobgoblin"
            "The Orc"
            "The Giant"
            "The Hill Giant"
            "The Storm Giant"
            "The Cloud Giant"
            "The Hero"
            "The Witch"
            "The Owlbear"
            "The Keeper"
            "The Frostmaiden"
            "The High One"
            "The Black Hand"
            "The Quiet One"
            "The Watcher"
            "The Satyr"
            "The Dryad"
            "Doombringer"
            "The Morninglord"
            "Mistshadow"
            "Joybringer"
            "The Beastlord"
            "The Reaper"
            "Binder"
            "The Moonmaiden"
            "The Dark Lady"
            "Lady Firehair"
            "The Stormlord"
            "Foehammer"
            "The Lady Luck"
            "Grimjaw"
            "The Wavemother"
            "The Coinmaiden"
            "The Lover"
            "The Beholder"
            "The Hunter"
            "The Enchantress"
            "The Beast"
            "The Angel"
            "The Imp"]
   ::post-2 ["Purse"
             "Hump"
             "Wings"
             "Hoofs"
             "Talons"
             "Hearth"
             "Goblet"
             "Mug"
             "Horn"
             "Horns"
             "Cup"
             "Plate"
             "Hindquarters"
             "Small Clothes"
             "Shield"
             "Helm"
             "Mace"
             "Crown"
             "Dagger"
             "Spear"
             "Sword"
             "Shield"
             "Dog"
             "Goat"
             "Maiden"
             "Mistress"
             "Rest"
             "Respite"
             "Kiss"
             "Caress"
             "Embrace"
             "Steed"
             "Companion"
             "Torch"
             "Bow"
             "Quiver"
             "Hand"
             "Foot"
             "Finger"
             "Toe"
             "Hoard"
             "Lair"
             "Moustache"
             "Eye"
             "Skull"
             "Fist"
             "Tattoo"
             "Secret"
             "Guantlet"
             "Tryst"
             "Whisper"
             "Flute"
             "Harp"
             "Table"
             "Chair"
             "Throne"]})

(defn random-tavern-name-1 []
  (str "The "
       (random-item tavern-names ::pre)
       " "
       (random-item tavern-names ::post)))

(defn random-tavern-name-2 []
  (str (random-item tavern-names ::pre-2)
       "'s "
       (random-item tavern-names ::post-2)))

(defn random-tavern-name []
  (rand-nth [(random-tavern-name-1)
             (random-tavern-name-2)]))
